services:
  tp1-grafana:
    image: grafana/grafana-enterprise:latest
    container_name: tp1-grafana
    restart: unless-stopped
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - tp1-grafana-data:/var/lib/grafana
      - ${SQLITE_FOLDER}:/var/lib/grafana/sqlite
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${GRAFANA_PORT}:3000"
    expose:
      - 3000
    networks:
      tp1-network:

volumes:
  tp1-grafana-data:
    name: tp1-grafana-data

networks:
  tp1-network:
    name: tp1-network
